#!/bin/sh

SHORT_DESCRIPTION="give it an rpm/deb/apk package name and get url from official repo."

#******************************************************************************#
#                                 functions                                    #
#******************************************************************************#

usage() {
cat >&2 <<-EOF

$SHORT_DESCRIPTION

Usage:

  curl https://sh.polyverse.io | sh -s get-package-url [<options>] <package_name>

Options:

  --help                 Display usage.

EOF
}

apk_alpine() {
        (>&2 echo "error: support for alpine not yet implemented.")
        return 1
}

deb_ubuntu() {
	FILENAME="$1"
	FIRST_LETTER=${FILENAME:0:1}

	URLs=""
	F1="$(echo $FILENAME | awk -F'_' '{print $1}')"
	F2=""
	while true; do
		URLs="$URLs http://archive.ubuntu.com/ubuntu/pool/main/$FIRST_LETTER/$F1"
		F2="$(echo $F1 | sed -e 's/\(-.*\)*$//g')"

		if [ "$F1" = "$F2" ]; then
			return 0
		fi

		F1="$F2"
	done

	return 1
}

rpm_fedora() {
	FILENAME="$1"
	RELEASE="$(echo $FILENAME | sed 's/.*fc\([0-9][0-9]\).*/\1/')"
	FIRST_LETTER=${FILENAME:0:1}

	if [ -z "$RELEASE" ]; then
		(>&2 echo "error: unable to determine fedora release for '$FILENAME'.")
		return 1
	fi

	URLs=""
	URLs="$URLs http://download.fedoraproject.org/pub/fedora/linux/updates/${RELEASE}/Everything/x86_64/Packages/${FIRST_LETTER}"
	URLs="$URLs http://download.fedoraproject.org/pub/fedora/linux/releases/${RELEASE}/Everything/x86_64/os/Packages/${FIRST_LETTER}"
	URLs="$URLs http://archives.fedoraproject.org/pub/archive/fedora/linux/releases/${RELEASE}/Everything/x86_64/os/Packages/${FIRST_LETTER}"
	URLs="$URLs http://archives.fedoraproject.org/pub/archive/fedora/linux/updates/${RELEASE}/x86_64/${FIRST_LETTER}"

	return 0
}

rpm_centos() {
	MAJOR_RELEASES="6 7"
	POINT_RELEASES="6.0 6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.0.1406 7.1.1503 7.2.1511 7.3.1611"

	URLs=""
	for MAJOR_RELEASE in $MAJOR_RELEASES; do
		URLs="$URLs http://mirror.centos.org/centos/${MAJOR_RELEASE}/os/x86_64/Packages"
		URLs="$URLs http://mirror.centos.org/centos/${MAJOR_RELEASE}/updates/x86_64/Packages"
	done

	for POINT_RELEASE in $POINT_RELEASES; do
		URLs="$URLs http://vault.centos.org/${POINT_RELEASE}/os/x86_64/Packages"
		URLs="$URLs http://vault.centos.org/${POINT_RELEASE}/updates/x86_64/Packages"
	done

	return 0
}

get_format() {
	FILENAME="$1"
	FORMAT="${FILENAME##*.}"

	if [ "$FORMAT" != "rpm" ] && [ "$FORMAT" != "apk" ] && [ "$FORMAT" != "deb" ]; then
		(>&2 echo "error: unsupported type '$FORMAT'")
		return 1
	fi

	echo "$FORMAT"
	return 0
}

get_project() {
	FILENAME="$1"
	FORMAT="$(get_format $FILENAME)"
	PROJECT=""

	case $FORMAT in
		apk)
			PROJECT="alpine"
			;;
		deb)
			PROJECT="ubuntu"
			;;
		rpm)
			if [ ! -z "$(echo "$FILENAME" | tr "." "\n" | grep -e "fc[0-9][0-9]")" ]; then
				PROJECT="fedora"
			else
				PROJECT="centos"
			fi
			;;
		*)
			(>&2 echo "error: unable to determine project for type '$FORMAT'")
			return 1
	esac
	
	echo "$PROJECT"
	return 0		
}

GetPackageURL() {
        FILENAME="$1"

        for URL in $URLs; do
                if [ ! -z "$(curl -sIL $URL/$FILENAME | grep "200 OK")" ]; then
                        echo "$URL/$FILENAME"
                        return 0
                fi
        done

        return 1
}

#******************************************************************************#
#                                    main                                      #
#******************************************************************************#

shift

if [ $# -eq 0 ] || [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
	usage
	exit 1
fi

FORMAT="$(get_format $1)"
if [ $? -ne 0 ]; then exit 1; fi

PROJECT="$(get_project $1)"
if [ $? -ne 0 ]; then exit 1; fi

# call function called <format>_<project> to populate LOCS variable
${FORMAT}_${PROJECT} $1
if [ $? -ne 0 ]; then exit 1; fi

RESULT="$(GetPackageURL $1)"
if [ $? -ne 0 ]; then
	(>&2 echo "Not found.")
	exit 1
fi

# write the final result to stdout
echo "$RESULT"
exit 0
