#!/bin/sh

        ####################################################################################################

usage() {
  echo "Usage: plv <subcommand>"
  echo
  echo "Available subcommands:"
  echo
  echo " help                Display help."
  echo " fix_dpkg_status     apt-based installations may incorrectly mark an identical package coming from"
  echo "                     repo.polyverse.io as \"upgrade\" instead of \"reinstall\". This is due to slight"
  echo "                     differences in the packages metadata (e.g., \"Installed-Size:\"). This subcommand"
  echo "                     will reconcile these records in /var/lib/dpkg/status."
  echo
  echo "If you encounter any issues, please contact us at support@polyverse.io, or create a GitHub issue at"
  echo "https://github.com/polyverse/plv."
}

usage
