#!/bin/sh

SHORT_DESCRIPTION="Output basic information about your host."

echo "os:"
echo "  distro: $(cat /etc/os-release 2>/dev/null | grep "^ID=" | cut -d '=' -f2 | tr -d '"')"
echo "  release: $(cat /etc/os-release 2>/dev/null | grep "VERSION_ID=" | cut -d "=" -f2 | tr -d '"')"
echo "  codename: $(cat /etc/*-release 2>/dev/null | grep "^DISTRIB_CODENAME=" | cut -d '=' -f2 | tr -d '"')"
echo "  arch: $(uname -m)"
echo "host:"
echo "  whoami: $(whoami)"
echo "  hostname: $HOSTNAME"
