#!/bin/sh

SHORT_DESCRIPTION="Output basic information about your host."

# make sure we're able to retrieve the distro release id (e.g., alpine, centos, ubuntu) and version id.
DISTRO="$(cat /etc/os-release 2>/dev/null | grep "^ID=" | cut -d '=' -f2 | tr -d '"')"
RELEASE="$(cat /etc/os-release 2>/dev/null | grep "VERSION_ID=" | cut -d "=" -f2 | tr -d '"')"
CODENAME="$(cat /etc/*-release 2>/dev/null | grep "^DISTRIB_CODENAME=" | cut -d '=' -f2 | tr -d '"')"
ARCH="$(uname -m)"

# Try to get PFRAC components from older meta-data in /etc (for CentOS and RHEL)
if [ -z "$DISTRO" ] || [ -z "$RELEASE" ] || [ -z "$ARCH" ]; then
        if [ ! -z "$(cat /etc/*-release | grep ^CentOS)" ]; then
                DISTRO="centos"
                RELEASE="$(cat /etc/*-release | grep ^CentOS | head -n 1 | sed 's/.*release //' | awk '{print $1}')"
        elif [ ! -z "$(cat /etc/*-release | grep ^Red)" ]; then
                DISTRO=rhel
                RELEASE="$(cat /etc/*-release | grep ^Red | head -n 1 | sed 's/.*release //' | awk '{print $1}')"
        else
                echo "Could not determine Linux distro. DISTRO='$DISTRO', RELEASE='$RELEASE', ARCH='$ARCH'. Exiting..." >&2
                exit 1
        fi
fi

echo "os"
echo "=="
echo "distro: $DISTRO"
echo "release: $RELEASE"
echo "codename: $CODENAME"
echo "arch: $ARCH"
echo
echo "host"
echo "===="
echo "whoami: $(whoami)"
echo "hostname: $HOSTNAME"
