#!/bin/bash

SHORT_DESCRIPTION="Scan all all processes that match parameter 1 and for each of those processes, get list of open .so files and look for see the number of times that the string given in parameter 2 is found."

if [ $(id -u) -ne 0 ]; then
        echo "This script must be run as root. Please try running this again as a sudo or root user." 1>&2
        exit 1
fi

shift
if [[ $# != 2 ]] ; then
	echo "usage: plv scan-pname pname string"
	exit 1
fi

pname=${1}
string=${2}

which lsof >& /dev/null
if [[ $? != 0 ]]; then
  echo "ERROR: Need to first install the 'lsof' package on this host (e.g., 'yum install lsof')"
  exit 1
fi
which pgrep >& /dev/null
if [[ $? != 0 ]]; then
  echo "ERROR: Need to first install the 'pgrep' package on this host (e.g., 'yum install procps-ng')"
  exit 1
fi

for pid in $(pgrep $pname); do
  echo "PID ${pid}:"
  liblist=$(lsof -p $pid | grep '\.so' |  sed -e 's/^.* \//\//'  -e 's/;.*$//')
  for lib in $liblist ; do
    numFound=$(strings $lib | grep -i -- $string | wc -l)
    echo "$numFound     $lib"
  done
done

