#!/bin/bash

# set the environment variable PV_BASE_URL to test non-prod version
if [ -z "$PV_BASE_URL" ]; then PV_BASE_URL="https://sh.polyverse.io"; fi

main() {
	PV_INFO="$(curl -s $PV_BASE_URL/main.sh | PV_BASE_URL=$PV_BASE_URL sh -s info)"
        if [ $? -ne 0 ]; then
                (>&2 echo "Unable to determine Linux distro info: $PV_INFO. Please contact support@polyverse.io.")
                return 1
        fi

	PV_DISTRO="$(echo "$PV_INFO" | grep ^DISTRO | awk -F= '{print $2}')"
	if [ "$PV_DISTRO" != "ubuntu" ]; then
		(>&2 echo "This script is only intended for Ubuntu.")
		return 1
	fi

	# run apt-get update in case it wasn't run after the Polymorphic Linux install
	RESULT="$(apt-get update -y 2>&1)"
	if [ $? -ne 0 ]; then
		echo "Error: command 'apt update -y' returned non-zero."
		echo "$RESULT"
		return 1
	fi

	downloadAndReplacePackagesWithDpkg

	return 0
}

parseCommandLine() {
	if [ "$1" = "ubuntu-replace-packages" ]; then
		shift
	fi
}

downloadAndReplacePackagesWithDpkg() {
	mkdir -p /tmp/pv/info /tmp/pv/triggers

	cd /var/lib/dpkg/info
	mv /var/lib/dpkg/info/*.pre* /tmp/pv/info/
	mv /var/lib/dpkg/info/*.post* /tmp/pv/info/
	mv /var/lib/dpkg/info/*.triggers /tmp/pv/info/
	mv /var/lib/dpkg/info/*.config /tmp/pv/info/

	#ls -al /var/lib/dpkg/triggers/
	mv /var/lib/dpkg/triggers/* /tmp/pv/triggers
	#ls -al /var/lib/dpkg/triggers/

	# since we're downloading deb files, let's cd to a folder that is permissive
	cd /tmp

	FILES_MOVED="$(ls /tmp/pv/info 2>/dev/null | wc -l)"
	(>&2 echo "Temporarily moved $FILES_MOVED files.")

	# output of 'apt list --installed' looks like:
	#
	#   adduser/xenial,now 3.113+nmu3ubuntu4 all [installed]
	#   apt/xenial-updates,now 1.2.29ubuntu0.1 amd64 [installed]
	#   apt-transport-https/xenial-updates,now 1.2.29ubuntu0.1 amd64 [installed]
	#
	APT_LIST_INSTALLED="$(apt list --installed 2>/dev/null | grep -v Listing)"

	# create list that contains the installed package names only
	PACKAGES="$(echo "$APT_LIST_INSTALLED" | awk -F/ '{print $1}')"

	for PACKAGE in $PACKAGES; do
		PACKAGE_VER="$(echo "$APT_LIST_INSTALLED" | grep "^${PACKAGE}/" | awk '{print $2}')"

		LIST="$LIST $PACKAGE=$PACKAGE_VER"
	done
	apt-get download $LIST | tee list.txt

	REPLACED_COUNT=0
	SKIPPED_COUNT=0

	# we're only interested in replacing the specific <package>=<version> that's already installed
	for PACKAGE in $PACKAGES; do
		PACKAGE_VER="$(echo "$APT_LIST_INSTALLED" | grep "^${PACKAGE}/" | awk '{print $2}')"
		PACKAGE_VER_ENCODED="$(echo "$PACKAGE_VER" | sed 's/:/%3a/g')"

		DEB_FILENAME="$(ls ${PACKAGE}_${PACKAGE_VER_ENCODED}*.deb | xargs)"

		if [ ! -z "$(cat list.txt | grep repo.polyverse.io | grep $PACKAGE | grep $PACKAGE_VER)" ]; then
			# implementation of https://askubuntu.com/questions/482928/ignore-apt-get-postinstall-scripts-automatically

			dpkg --unpack $DEB_FILENAME | grep -v "Reading database"
			rm -f /var/lib/dpkg/triggers/*

			# scripts, control files, etc. are all extracted by default to /var/lib/dpkg/info
			rm -f /var/lib/dpkg/info/*.pre*
			rm -f /var/lib/dpkg/info/*.post*
			rm -f /var/lib/dpkg/info/*.triggers
			rm -f /var/lib/dpkg/info/*.config
			rm -f /var/lib/dpkg/info/*.conffiles

			# this should be a no-op, but run it to be sure
			dpkg --configure $PACKAGE
			REPLACED_COUNT=$((REPLACED_COUNT+1))
		else
			echo "Skipping $PACKAGE ($PACKAGE_VER)"
			SKIPPED_COUNT=$((SKIPPED_COUNT+1))
		fi

		# clean-up
		rm -f $DEB_FILENAME >/dev/null 2>&1
	done

	# restore all the pre/post/trigger files
	mv /tmp/pv/info/*.* /var/lib/dpkg/info/
	mv /tmp/pv/triggers/* /var/lib/dpkg/triggers

	#rm -frd /tmp/pv

	echo "Polyverse replaced $REPLACED_COUNT and skipped $SKIPPED_COUNT packages."

	# -f will correct broken dependencies, but this should be a no-op
	# -y = assume yes
	(>&2 apt-get install -yf)

	return 0
}

main "$@"
exit $?
